name: generate animation

on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: lusqua/lusqua@master
        id: snake-gif
        with:
          github_user_name: lusqua
          svg_out_path: dist/snk_gif.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN_GH_PAGES }}